#服务端口
server:
  port: 8201

spring:
  application:
    name: service-hosp   #服务名
  profiles:
    active: dev    #环境设置：dev、test、prod
    #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&&useSSL=false
    username: root
    password: root

#  #mongodb地址
#  data:
#    mongodb:
#      host: 192.168.44.163
#      port: 27017
#      database: yygh_hosp
#
#  #rabbitmq地址
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

  #返回json的全局时间模式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://192.168.128.128:27017/yygh_hosp

  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    #设置sentinel地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858

#mybatis-plus:
#  mapper-locations: classpath:com/mingri/yygh/mapper/xml/*.xml

##开启sentinel
#feign:
#  sentinel:
#    enabled=true: true
logging:
  lever:
    root: DEBUG
