# 服务端口
server:
  port: 8160
  # 服务名
spring:
  application:
    name: service-user

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver    #zeroDateTimeBehavior=convertToNull可以插入到时间戳中
    url:  jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  #返回json的全局时间格式
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8

  redis:
    host: 192.168.128.128
    port: 6379
    password: 123456
    database: 0
    timeout: 1800000

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848

  #配置mapper xml文件的路径
mybatis-plus:
    mapper-locations: classpath:com/mingri/yygh/user/mapper/xml/*.xml

wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback

yygh:
  baseUrl: http://localhost:3000