# 服务端口
server:
  port: 8206
  # 服务名
spring:
  application:
    name: service-order
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://192.168.128.128:27017/yygh_hosp

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #rabbitmq地址
  rabbitmq:
    host: 192.168.128.128
    port: 5672
    username: guest
    password: guest

  redis:
    host: 192.168.128.128
    port: 6379
    database: 0
    password: 123456
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0


  #关联的公众号appid
weixin:
  appid: wx74862e0dfcf69954
  #商户号
  partner: 1558950191
  #商户key
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #退款证书
  cert: D:\\Download\\JAVA\\javaidea\\projects\\Hospital\\service\\service_order\\src\\main\\resources\\cert\\apiclient_cert.p12

mybatis-plus:
  mapper-locations: classpath:com/mingri/yygh/order/mapper/xml/*.xml