# 服务端口
server:
  port: 81

  # 服务名
spring:
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled:  true

      routes[0]:
        id: service-hosp   #设置路由id
        uri: lb://service-hosp    #设置路由的uri
        predicates: Path=/*/hosp/**    #设置路由断言,代理servicerId为auth-service的/auth/路径

      routes[1]:
        id: service-cmn      #设置路由id
        uri: lb://service-cmn     #设置路由的uri
        predicates: Path=/*/cmn/**    #设置路由断言,代理servicerId为auth-service的/auth/路径

      routes[2]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**

      routes[3]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/*/msm/**

      routes[4]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/ucenter/**

      routes[5]:
        id: service-oss
        uri: lb://service-oss
        predicates: Path=/*/oss/**

      routes[6]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/user/**

      routes[7]:
        id: service-order
        uri: lb://service-order
        predicates: Path=/*/order/**

      routes[8]:
        id: service-order
        uri: lb://service-order
        predicates: Path=/*/weixin/**

      routes[9]:
        id: service-statistics
        uri: lb://service-statistics
        predicates: Path=/*/statistics/**